#!/bin/bash

#PICPATH=/media/paul/fa3ea422-7078-4c0a-a7b8-37ed13d211ac/paul/pictures/
PICPATH=/media/paul/Main/pictures/

if [ $# -eq 0 ]; then
	rsync -aivn --progress ~/pictures/ $PICPATH | less
fi
if [ $# -eq 1 ]; then
	rsync -a --progress ~/pictures/ $PICPATH
fi