#!/bin/bash

#$PATH=/media/paul/fa3ea422-7078-4c0a-a7b8-37ed13d211ac/paul/pictures/
$PATH=/media/paul/Main/pictures/

if [ "$1" == "dryrun" ]; then
	rsync -aivn --progress ~/pictures/ $PATH | less
fi
if [ "$1" == "go" ]; then
	rsync -a --progress ~/pictures/ $PATH
fi
if [ "$#" -eq 0 ]; then
	echo "Usage $0 subcommand"
	echo -e "\tSubcommands: go, dryrun"
fi
